/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ventanas.pestanas.minipestanas;

/**
 *
 * @author Jhoel Rivera
 */
public class slash_filtro extends javax.swing.JPanel {

    /**
     * Creates new form slash_filtro
     */
    public slash_filtro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BFiltro1 = new javax.swing.JButton();
        BFiltro2 = new javax.swing.JButton();
        BFiltro3 = new javax.swing.JButton();
        BFiltro4 = new javax.swing.JButton();
        BFiltro5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BFiltro1.setBackground(new java.awt.Color(153, 255, 255));
        BFiltro1.setForeground(new java.awt.Color(0, 0, 0));
        BFiltro1.setText("jButton1");
        add(BFiltro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 150, -1));

        BFiltro2.setBackground(new java.awt.Color(153, 255, 255));
        BFiltro2.setForeground(new java.awt.Color(0, 0, 0));
        BFiltro2.setText("jButton1");
        add(BFiltro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, -1));

        BFiltro3.setBackground(new java.awt.Color(153, 255, 255));
        BFiltro3.setForeground(new java.awt.Color(0, 0, 0));
        BFiltro3.setText("jButton1");
        add(BFiltro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 140, -1));

        BFiltro4.setBackground(new java.awt.Color(153, 255, 255));
        BFiltro4.setForeground(new java.awt.Color(0, 0, 0));
        BFiltro4.setText("jButton1");
        BFiltro4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFiltro4ActionPerformed(evt);
            }
        });
        add(BFiltro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 130, -1));

        BFiltro5.setBackground(new java.awt.Color(153, 255, 255));
        BFiltro5.setForeground(new java.awt.Color(0, 0, 0));
        BFiltro5.setText("jButton1");
        add(BFiltro5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 140, -1));

        jButton1.setBackground(new java.awt.Color(102, 0, 0));
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 20, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void BFiltro4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFiltro4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BFiltro4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BFiltro1;
    private javax.swing.JButton BFiltro2;
    private javax.swing.JButton BFiltro3;
    private javax.swing.JButton BFiltro4;
    private javax.swing.JButton BFiltro5;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
