/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;
import java.awt.Color;
import javax.swing.*; 
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener; 
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import ventanas.logicaVentanas.Usuario;
import java.util.ArrayList; import java.util.List;
/**
 *
 * @author Jhoel Rivera
 */
public class Login extends javax.swing.JFrame {
    private Registrarse v2;

    /**
     * Creates new form NewJFrame
     */
    public Login() {
        initComponents();
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelRound1 = new components.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        ContrasenaEnt = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        UsuarioEnt = new javax.swing.JTextField();
        estadoAcceso = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setForeground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_Login/login.png"))); // NOI18N
        panelRound1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 30, 40));

        ContrasenaEnt.setText("********");
        ContrasenaEnt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ContrasenaEntMousePressed(evt);
            }
        });
        ContrasenaEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContrasenaEntActionPerformed(evt);
            }
        });
        panelRound1.add(ContrasenaEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 200, 40));

        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("Eres nuevo? Registrarse ");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelRound1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 200, 20));

        jButton2.setForeground(new java.awt.Color(153, 51, 255));
        jButton2.setText("Ingresar");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelRound1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 140, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_Login/password3.png"))); // NOI18N
        panelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 30, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_Login/txtIniciar Sesion_1.png"))); // NOI18N
        panelRound1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 310, 90));

        UsuarioEnt.setText("Usuario");
        UsuarioEnt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textDisable(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textDisableL(evt);
            }
        });
        UsuarioEnt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UsuarioEntMousePressed(evt);
            }
        });
        UsuarioEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioEntActionPerformed(evt);
            }
        });
        panelRound1.add(UsuarioEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 200, 40));

        estadoAcceso.setBorder(null);
        estadoAcceso.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        panelRound1.add(estadoAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 200, 30));

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 360, 460));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_Login/Screenshot 2024-11-26 202151.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 610));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void inicializarComponentes() {
        estadoAcceso.setVisible(false);
        v2=new Registrarse();
    }

    public static List<Usuario> leerUsuarios() throws IOException {
    List<Usuario> usuarios = new ArrayList<>(); 
    try (BufferedReader reader = new BufferedReader(new FileReader("usuarios.txt"))) {
        String line;
        while ((line = reader.readLine()) != null) {
            String[] parts = line.split(","); 
            if (parts.length == 3) { 
                usuarios.add(new Usuario(parts[0], parts[1], parts[2])); 
            }
        } 
    }
    return usuarios;
}
   public static Usuario validarCredenciales(String username, String password) throws IOException { 
       List<Usuario> usuarios = leerUsuarios();
       for (Usuario usuario : usuarios) {
           if (usuario.getUsername().equals(username) && usuario.getPassword().equals(password)) {
               return usuario;
           } 
       } 
       return null;
   }
   private void mostrarMensajeEstado(String mensaje, boolean esExitoso) { 
       estadoAcceso.setText("");
       estadoAcceso.setText("");
       if (!esExitoso) { 
           estadoAcceso.setText(mensaje);
           estadoAcceso.setForeground(Color.RED);
           estadoAcceso.setVisible(true);
       } 
       jPanel1.revalidate();
       jPanel1.repaint();
   }
   private void setV1(Login v1){
       this.v2=v2;
  }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        v2.setVisible(true);
        estadoAcceso.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           String username = UsuarioEnt.getText(); 
           char[] passwordChars = ContrasenaEnt.getPassword();
           String password = new String(passwordChars); 
          try {
        Usuario usuario = validarCredenciales(username, password);
        if (usuario != null) { // Si las credenciales son válidas
            if ("admin".equalsIgnoreCase(usuario.getRol())) {
                
                 variablesGlobales.setAdminUsername(username);
                 
                VentanaAdmin ventanaAdmin = new VentanaAdmin(username);
                ventanaAdmin.setVisible(true);
            } else if ("user".equalsIgnoreCase(usuario.getRol())) {
                
                variablesGlobales.setUsuarioActual(username);
                
                VentanaUser ventanaUser = new VentanaUser(username );
                ventanaUser.setVisible(true);
            } else {
                mostrarMensajeEstado("Rol no reconocido.", false);
            }
            this.setVisible(false); // Ocultar la ventana actual
        } else {
            mostrarMensajeEstado("Usuario y/o contraseña incorrectos", false);
        }
    } catch (IOException e) {
        mostrarMensajeEstado("Ocurrió un error inesperado, inténtelo más tarde.", false);
        e.printStackTrace();
    }       
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private List<String> cargarTareasUsuario(String username) {
    List<String> tareas = new ArrayList<>();
    File archivoTareas = new File(username + ".txt");
    if (archivoTareas.exists()) {
        try (BufferedReader reader = new BufferedReader(new FileReader(archivoTareas))) {
            String tarea;
            while ((tarea = reader.readLine()) != null) {
                tareas.add(tarea);
            }
        } catch (IOException e) {
            e.printStackTrace();
            mostrarMensajeEstado("No se pudieron cargar las tareas del usuario.", false);
        }
    }
    return tareas;
}

    
    
    
    
    
    
    
    
    
    
    
    private void crearArchivoTareas(String username) {
    File archivoTareas = new File(username + ".txt");
    try {
        if (archivoTareas.createNewFile()) {
            System.out.println("Archivo de tareas creado para el usuario: " + username);
        } else {
            System.out.println("El archivo de tareas ya existe para el usuario: " + username);
        }
    } catch (IOException e) {
        e.printStackTrace();
        mostrarMensajeEstado("No se pudo crear el archivo de tareas para el usuario.", false);
    }
}
    private void verificarOCrearArchivoTareas(String username) {
    File archivoTareas = new File(username + ".txt");
    if (!archivoTareas.exists()) {
        try {
            if (archivoTareas.createNewFile()) {
                System.out.println("Archivo de tareas creado para el usuario: " + username);
            } else {
                System.out.println("No se pudo crear el archivo de tareas para el usuario: " + username);
            }
        } catch (IOException e) {
            e.printStackTrace();
            mostrarMensajeEstado("No se pudo crear el archivo de tareas para el usuario.", false);
        }
    }
}
    private void ContrasenaEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContrasenaEntActionPerformed
         
    }//GEN-LAST:event_ContrasenaEntActionPerformed

    private void UsuarioEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioEntActionPerformed
        
    }//GEN-LAST:event_UsuarioEntActionPerformed

    private void textDisable(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textDisable
        // TODO add your handling code here:
    }//GEN-LAST:event_textDisable

    private void textDisableL(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textDisableL
        // TODO add your handling code here:
    }//GEN-LAST:event_textDisableL

    private void UsuarioEntMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuarioEntMousePressed
      if (UsuarioEnt.getText().equals("Usuario")) {
          UsuarioEnt.setText(""); UsuarioEnt.setForeground(Color.black); 
      } 
      if (String.valueOf(ContrasenaEnt.getPassword()).isEmpty()) {
          ContrasenaEnt.setText("********"); 
          ContrasenaEnt.setForeground(Color.gray);
      }
    }//GEN-LAST:event_UsuarioEntMousePressed

    private void ContrasenaEntMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContrasenaEntMousePressed
         if (String.valueOf(ContrasenaEnt.getPassword()).equals("********")) {
             ContrasenaEnt.setText(""); 
             ContrasenaEnt.setForeground(Color.black);
         } 
         if (UsuarioEnt.getText().isEmpty()) {
             UsuarioEnt.setText("Usuario"); 
             UsuarioEnt.setForeground(Color.gray); 
         }
    }//GEN-LAST:event_ContrasenaEntMousePressed

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ContrasenaEnt;
    private javax.swing.JTextField UsuarioEnt;
    private javax.swing.JTextField estadoAcceso;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private components.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables
}

